// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxeSJ3eHgUw5C4ouS7yH0RXvPn2p0HxO0',
    appId: '1:778947217768:web:01699ba903081c68f2eedd',
    messagingSenderId: '778947217768',
    projectId: 'babbyshop-4da12',
    authDomain: 'babbyshop-4da12.firebaseapp.com',
    storageBucket: 'babbyshop-4da12.appspot.com',
    measurementId: 'G-6WJJKQFT05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNFeUzS9BOKdjlbwoRzjsXoTwuWDNjxQs',
    appId: '1:778947217768:android:187828885325441ef2eedd',
    messagingSenderId: '778947217768',
    projectId: 'babbyshop-4da12',
    storageBucket: 'babbyshop-4da12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ns4gw9_fnEsoJD-rG3tO9CifrWs6VFA',
    appId: '1:778947217768:ios:1ba2f6f3ea92317af2eedd',
    messagingSenderId: '778947217768',
    projectId: 'babbyshop-4da12',
    storageBucket: 'babbyshop-4da12.appspot.com',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ns4gw9_fnEsoJD-rG3tO9CifrWs6VFA',
    appId: '1:778947217768:ios:d64e142793b11273f2eedd',
    messagingSenderId: '778947217768',
    projectId: 'babbyshop-4da12',
    storageBucket: 'babbyshop-4da12.appspot.com',
    iosBundleId: 'com.example.babyshophub.RunnerTests',
  );
}
